apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duser-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Deepthi-mygit/argo-rollout-duser-blue-green.git
    path: duser-rollout
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}